<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="usecases\commands\**" />
    <Compile Remove="usecases\queries\**" />
    <EmbeddedResource Remove="usecases\commands\**" />
    <EmbeddedResource Remove="usecases\queries\**" />
    <None Remove="usecases\commands\**" />
    <None Remove="usecases\queries\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Journey_of_faith.Domain\Journey_of_faith.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="common\dtos\" />
    <Folder Include="usecases\auth\commands\NewFolder\" />
    <Folder Include="usecases\auth\dtos\" />
  </ItemGroup>

</Project>
